FileSearchEngine/Models/ErrorViewModel.cs
namespace FileSearchEngine.Models;

public class ErrorViewModel {
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

FileSearchEngine/Controllers/ElasticController.cs
using System.Diagnostics;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Mvc;
using FileSearchEngine.Models;

namespace FileSearchEngine.Controllers;

public sealed class ElasticController(ILogger<ElasticController> logger) : Controller
{
    public IActionResult Index()
    {
        return View();
    }
    
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    public async Task<IActionResult> Search(string searchPhrase, int count = 5)
    {
        logger.LogInformation("Search start");
        
        if (string.IsNullOrEmpty(searchPhrase))
            return Content("No search phrase provided");

        if (count is < 1 or > 100)
            count = 5;
        
        var resp = (await ElasticDatabase.SearchFiles(searchPhrase, count)).ToList();
        if(resp.Count == 0)
            return Content("No results found");
        
        ViewBag.SearchResult = resp;
        logger.LogInformation("Search end");
        return Content(GetSearchResultString(resp));
    }
    
    public async Task<IActionResult> SearchKnn(string searchPhrase, int count = 5)
    {
        logger.LogInformation("Search start");
        
        if (string.IsNullOrEmpty(searchPhrase))
            return Content("No search phrase provided");

        if (count is < 1 or > 100)
            count = 5;
        
        var resp = (await ElasticDatabase.SearchFilesKnn(searchPhrase, count)).ToList();
        if(resp.Count == 0)
            return Content("No results found");
        
        ViewBag.SearchResult = resp;
        logger.LogInformation("Search end");
        return Content(GetSearchResultString(resp));
    }

    private static string GetSearchResultString(IEnumerable<Article> articles)
    {
        return string.Join('\n', articles.Select(x => x.ToString()));
    }
}

FileSearchEngine/Controllers/FileController.cs
using Microsoft.AspNetCore.Mvc;

namespace FileSearchEngine.Controllers;

public sealed class FileController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
    
    public async Task<IActionResult> DeleteFile(string id)
    {
        if (string.IsNullOrEmpty(id))
        {
            return BadRequest(new { message = "No file id provided" });
        }

        if (!int.TryParse(id, out var parsed) || parsed < 0)
            return BadRequest("Invalid id provided");

        var response = await Model.RemoveFile(parsed);
        if (!response)
            return NotFound(new { message = "File not found" });
        return Ok(new { message = "File deleted successfully" });
    }
    
    public async Task<IActionResult> UploadFile(IFormFile? file)
    {
        if (file == null || file.Length == 0)
            return BadRequest(new { message = "No file uploaded" });
        
        if(file.ContentType != "text/plain")
            return BadRequest(new { message = "Only text files are accepted" });

        var content = await new StreamReader(file.OpenReadStream()).ReadToEndAsync();
        await Model.AddFile(file.FileName, content);
        return Ok(new { message = "File uploaded successfully" });
    }

    public IActionResult GetFileList()
    {
        var files = Database.GetFiles();
        var options = files.Select(f => 
            $"<option value='{f.Id}'>{f.Id} {f.Name}</option>").ToList();

        return Content(string.Join(Environment.NewLine, options));
    }
}

FileSearchEngine/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using FileSearchEngine.Models;

namespace FileSearchEngine.Controllers;

public sealed class HomeController(ILogger<HomeController> logger) : Controller
{
    public IActionResult Index()
    {
        return View();
    }
    
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

    public IActionResult Search(string searchPhrase, int count = 5)
    {
        logger.LogInformation("Search start");
        
        if (string.IsNullOrEmpty(searchPhrase))
            return Content("No search phrase provided");

        if (count is < 1 or > 100)
            count = 5;
        
        var resp = Model.SearchFiles(searchPhrase, count).ToList();
        if(resp.Count == 0)
            return Content("No results found");
        
        var articles = Database.GetFiles(resp).OrderBy(a => resp.IndexOf(a.Id)).ToList();
        ViewBag.SearchResult = articles;
        logger.LogInformation("Search end");
        return Content(GetSearchResultString(articles));
    }
    
    public IActionResult SearchTfIdf(string searchPhrase, int count = 5)
    {
        logger.LogInformation("Search start");
        
        if (string.IsNullOrEmpty(searchPhrase))
            return Content("No search phrase provided");

        if (count is < 1 or > 100)
            count = 5;
        
        var resp = Model.SearchFilesTfIdf(searchPhrase, count).ToList();
        if(resp.Count == 0)
            return Content("No results found");
        
        var articles = Database.GetFiles(resp).OrderBy(a => resp.IndexOf(a.Id)).ToList();
        ViewBag.SearchResult = articles;
        logger.LogInformation("Search end");
        return Content(GetSearchResultString(articles));
    }

    private static string GetSearchResultString(IEnumerable<Article> articles)
    {
        return string.Join('\n', articles.Select(x => x.ToString()));
    }
}

FileSearchEngine/Views/Elastic/Index.cshtml
@{
ViewData["Title"] = "Elastic search Page";
}

<div class="search-section">
    <div class="form-row">
        <div class="row">
            <div class="col">
                <label for="searchPhrase">Enter Search Phrase:</label>
            </div>
            <div class="col-1">
                <label for="resultsCount">Count:</label>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <input type="text"
                       id="searchPhrase"
                       name="searchPhrase"
                       class="form-control"
                       placeholder="Search..."
                       required>
            </div>
            <div class="col-1">
                <input type="number"
                       id="resultsCount"
                       name="resultsCount"
                       class="form-control"
                       placeholder="5"
                       required
                       min="1"
                       max="100"
                       value="5">
            </div>
        </div>
    </div>

    <button type="button" class="btn btn-primary mt-2" id="searchButton">Search</button>
    <button type="button" class="btn btn-primary mt-2" id="searchButtonKnn">SearchKnn</button>

    <br/>
    <label for="searchResult">Search Results:</label>
    <textarea id="searchResult" name="searchResult" class="form-control mt-2" rows="25" readonly></textarea>
</div>

<!-- JavaScript for AJAX Request -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('#searchButton').click(function () {
            let result = $('#searchResult');
            result.val(null);
            let searchPhrase = $('#searchPhrase').val();
            if (searchPhrase.trim() !== "") {
                let count = $('#resultsCount').val();
                let resultCount = parseInt(count, 10);
                if (resultCount === null || resultCount === -1 || resultCount < 1 || resultCount > 100) {
                    resultCount = 5;
                }
                // Make the AJAX request to the server
                $.ajax({
                    url: '@Url.Action("Search", "Elastic")',  // This calls the 'Search' action in the 'Home' controller
                    type: 'POST',
                    data: { searchPhrase: searchPhrase, count: resultCount },
                    success: function (data) {
                        // When the search is successful, update the result textarea
                        $('#searchResult').val(data);
                    },
                    error: function () {
                        $('#searchResult').val("An error occurred while searching.");
                    }
                });
            } else {
                result.val("Please enter a search phrase.");
            }
        });
        $('#searchButtonKnn').click(function () {
            let result = $('#searchResult');
            result.val(null);
            let searchPhrase = $('#searchPhrase').val();
            if (searchPhrase.trim() !== "") {
                let count = $('#resultsCount').val();
                let resultCount = parseInt(count, 10);
                if (resultCount === null || resultCount === -1 || resultCount < 1 || resultCount > 100) {
                    resultCount = 5;
                }
                // Make the AJAX request to the server
                $.ajax({
                    url: '@Url.Action("SearchKnn", "Elastic")',
                    type: 'POST',
                    data: { searchPhrase: searchPhrase, count: resultCount },
                    success: function (data) {
                        $('#searchResult').val(data);
                    },
                    error: function () {
                        $('#searchResult').val("An error occurred while searching.");
                    }
                });
            } else {
                result.val("Please enter a search phrase.");
            }
        });
    });

</script>

FileSearchEngine/Views/File/Index.cshtml
<body>
<div class="container">
    <h2>File Management</h2>

    <form id="deleteFileForm" method="post">
        <label for="fileList">Select a file to delete:</label>
        <select id="fileList" name="id">
            @foreach (var item in Database.GetFiles())
            {
            <option value="@item.Id">@item.Id @item.Name</option>
            }
        </select>

        <button type="submit">Delete File</button>
    </form>
    
    <hr>

    <form id="addFileForm" method="post" enctype="multipart/form-data">
        <label for="fileUpload">Upload a new file:</label>
        <input type="file" id="fileUpload" name="fileUpload" />
        <button type="submit">Upload File</button>
    </form>
</div>

<script>
    function refreshFileList() {
        fetch('@Url.Action("GetFileList", "File")') // Replace "ControllerName" with your actual controller name
            .then(response => response.text())
            .then(data => {
                // Replace the contents of the select element with the updated list
                document.getElementById('fileList').innerHTML = data;
            })
            .catch(error => {
                console.error('Error fetching file list:', error);
            });
    }
    
    document.getElementById('deleteFileForm').addEventListener('submit', function (event) {
        event.preventDefault(); // Prevent page redirection

        let formData = new FormData(this); // Get form data

        // Perform an AJAX request
        fetch('@Url.Action("DeleteFile", "File")', {
            method: 'POST',
            body: formData
        })
            .then(response => response.json())
            .then(data => {
                refreshFileList();
                alert(data?.message ?? "No response");
            })
            .catch(error => {
                console.error('Error:', error);
                alert('An error occurred while deleting the file.');
            });
    });
    document.getElementById('addFileForm').addEventListener('submit', function (event) {
        event.preventDefault(); // Prevent page redirection

        let formData = new FormData();
        formData.append('file', $('#fileUpload')[0].files[0]);
        
        // Perform an AJAX request to upload the file
        fetch('@Url.Action("UploadFile", "File")', {
            method: 'POST',
            body: formData
        })
            .then(response => response.json())
            .then(data => {
                refreshFileList();
                alert(data?.message ?? "No response");
            })
            .catch(error => {
                console.error('Error:', error);
                alert('An error occurred while uploading the file.');
            });
    });

</script>
</body>

FileSearchEngine/Views/Home/Index.cshtml
@{
ViewData["Title"] = "Home Page";
}

<div class="search-section">
    <div class="form-row">
        <div class="row">
            <div class="col">
                <label for="searchPhrase">Enter Search Phrase:</label>
            </div>
            <div class="col-1">
                <label for="resultsCount">Count:</label>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <input type="text"
                       id="searchPhrase"
                       name="searchPhrase"
                       class="form-control"
                       placeholder="Search..."
                       required>
            </div>
            <div class="col-1">
                <input type="number"
                       id="resultsCount"
                       name="resultsCount"
                       class="form-control"
                       placeholder="5"
                       required
                       min="1"
                       max="100"
                       value="5">
            </div>
        </div>
    </div>

    <button type="button" class="btn btn-primary mt-2" id="searchButton">Search</button>
    <button type="button" class="btn btn-primary mt-2" id="searchButtonStar">Search tfidf</button>

    <br/>
    <label for="searchResult">Search Results:</label>
    <textarea id="searchResult" name="searchResult" class="form-control mt-2" rows="25" readonly></textarea>
</div>

<!-- JavaScript for AJAX Request -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('#searchButton').click(function () {
            let result = $('#searchResult');
            result.val(null);
            let searchPhrase = $('#searchPhrase').val();
            if (searchPhrase.trim() !== "") {
                let count = $('#resultsCount').val();
                let resultCount = parseInt(count, 10);
                if (resultCount === null || resultCount === -1 || resultCount < 1 || resultCount > 100) {
                    resultCount = 5;
                }
                // Make the AJAX request to the server
                $.ajax({
                    url: '@Url.Action("Search", "Home")',  // This calls the 'Search' action in the 'Home' controller
                    type: 'POST',
                    data: { searchPhrase: searchPhrase, count: resultCount },
                    success: function (data) {
                        // When the search is successful, update the result textarea
                        $('#searchResult').val(data);
                    },
                    error: function () {
                        $('#searchResult').val("An error occurred while searching.");
                    }
                });
            } else {
                result.val("Please enter a search phrase.");
            }
        });
    });

    $(document).ready(function () {
        $('#searchButtonStar').click(function () {
            let result = $('#searchResult');
            result.val(null);
            let searchPhrase = $('#searchPhrase').val();
            if (searchPhrase.trim() !== "") {
                let count = $('#resultsCount').val();
                let resultCount = parseInt(count, 10);
                if (resultCount === null || resultCount === -1 || resultCount < 1 || resultCount > 100) {
                    resultCount = 5;
                }
                // Make the AJAX request to the server
                $.ajax({
                    url: '@Url.Action("SearchTfIdf", "Home")',  // This calls the 'Search' action in the 'Home' controller
                    type: 'POST',
                    data: { searchPhrase: searchPhrase, count: resultCount },
                    success: function (data) {
                        // When the search is successful, update the result textarea
                        $('#searchResult').val(data);
                    },
                    error: function () {
                        $('#searchResult').val("An error occurred while searching.");
                    }
                });
            } else {
                result.val("Please enter a search phrase.");
            }
        });
    });

</script>

FileSearchEngine/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - FileSearchEngine</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/FileSearchEngine.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FileSearchEngine</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Elastic" asp-action="Index">Elastic</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="File" asp-action="Index">Files</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - FileSearchEngine
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>